services:
  - type: web
    name: portfolio-backend
    env: java
    buildCommand: "./mvnw clean package -DskipTests || mvn clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    plan: free
